# ACX3300 Predictive Analytics in Accounting

## Project 1: Forecasting Earnings

Below are the details of the team members:

| Team members | Student ID |
|--------------|------------|
|  Student 1   |  xxxxxxxx |
| Student 2   | xxxxxxxx   |
|  Student 3  |   xxxxxxxx |

### Import packages

In [2]:
import pandas as pd

### Part 1: Data Preparation

In [3]:
accounting_data = pd.read_csv('accounting_data.csv')

In [6]:
accounting_data

,gvkey,datadate,fyear,at,ceq,che,csho,dlc,dltt,invt,...,mib,ni,oancf,oiadp,pi,pstk,rect,sale,txt,xsga
0,1004,20010531,2000,701.854,340.212,13.809,26.937,13.652,179.987,320.590,...,0.0,18.531,46.093,45.790,20.220,0.0,115.187,874.255,1.689,96.077
1,1004,20020531,2001,710.199,310.235,34.522,31.870,42.525,217.699,286.588,...,0.0,-58.939,-33.315,4.711,-98.229,0.0,77.528,638.721,-39.290,85.037
2,1004,20030531,2002,686.621,294.988,29.154,31.851,92.256,164.658,259.954,...,0.0,-12.410,34.733,3.573,-19.490,0.0,66.322,606.337,-7.080,78.845
3,1004,20040531,2003,709.292,301.684,41.010,32.245,3.392,248.666,247.245,...,0.0,3.504,14.572,20.811,1.707,0.0,104.661,651.958,-1.797,81.165
4,1004,20050531,2004,732.230,314.744,50.338,32.586,3.745,227.159,255.477,...,NaN,15.453,50.938,33.824,21.639,0.0,127.121,747.848,3.067,87.902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285486,347085,20210228,2020,192.079,56.357,65.057,21.383,4.790,4.662,0.000,...,0.0,20.965,61.795,53.058,45.863,0.0,18.128,150.924,13.088,53.686
285487,351491,20191231,2019,17847.000,3007.000,468.000,NaN,5561.000,215.000,2913.000,...,0.0,94.000,796.000,650.000,196.000,0.0,8114.000,13408.000,83.000,1132.000
285488,351491,20201231,2020,18841.000,2734.000,558.000,NaN,6205.000,199.000,2707.000,...,0.0,-492.000,674.000,67.000,-588.000,0.0,8569.000,12549.000,-140.000,1078.000
285489,351590,20191231,2019,62131.888,11054.622,6532.226,NaN,13242.877,12899.490,8473.601,...,0.0,1942.498,1425.172,2579.898,2952.463,0.0,15167.421,51894.216,988.643,7095.561
285490,351590,20201231,2020,60256.041,9914.300,9012.671,NaN,14229.582,10539.895,7567.413,...,0.0,-172.370,5026.460,154.290,402.599,0.0,12654.142,43409.566,560.505,6522.343

In [10]:
accounting_data[accounting_data.duplicated(['gvkey', 'fyear'], keep=False)]

,gvkey,datadate,fyear,at,ceq,che,csho,dlc,dltt,invt,...,mib,ni,oancf,oiadp,pi,pstk,rect,sale,txt,xsga
13,1004,20140531,2013,2199.5,999.5,89.2,39.560,69.7,564.3,632.9,...,0.0,72.9,139.8,142.6,105.3,0.0,297.9,2035.0,32.1,197.6
14,1004,20140531,2013,2159.8,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,72.9,NaN,NaN,NaN,NaN,NaN,1415.5,NaN,NaN
15,1004,20150531,2014,1515.0,845.1,54.7,35.423,69.0,85.0,566.7,...,0.0,10.2,-43.0,-8.6,-83.0,0.0,231.1,1594.3,-28.5,167.9
16,1004,20150531,2014,1454.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.2,NaN,NaN,NaN,NaN,NaN,1448.0,NaN,NaN
17,1004,20160531,2015,1442.1,865.8,31.2,34.515,12.0,136.1,563.7,...,0.0,47.7,32.1,66.1,59.3,0.0,242.7,1662.6,18.8,170.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285478,345980,20181231,2018,1193.0,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,-208.0,NaN,NaN,-208.0,NaN,NaN,1728.0,0.0,1673.0
285479,345980,20191231,2019,1366.0,-1439.0,1044.0,103.695,8.0,42.0,0.0,...,0.0,-129.0,-60.0,-144.0,-128.0,1536.0,95.0,1901.0,1.0,1602.0
285480,345980,20191231,2019,1366.0,NaN,NaN,NaN,NaN,42.0,NaN,...,NaN,-129.0,NaN,NaN,-128.0,NaN,NaN,1901.0,1.0,1602.0
285481,345980,20201231,2020,2397.0,1027.0,2129.0,587.000,14.0,38.0,0.0,...,0.0,-745.0,0.0,-631.0,-743.0,0.0,83.0,2541.0,2.0,2225.0
285482,345980,20201231,2020,2397.0,NaN,NaN,NaN,NaN,38.0,NaN,...,NaN,-745.0,NaN,NaN,-743.0,NaN,NaN,2541.0,2.0,2225.0

#### Data dictionary

| **Fieldnames** | **Definition**                                                 | **Description**                                                                                                                                                                                        |
|----------------|----------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| GVKEY      | A Unique Global Company Key                                    | A unique identifier that represents each company throughout Xpressfeed. All company data records are identified by a GVKEY. Except in rare circumstances |
| DATADATE   | Data Date                                                      | The reporting date for a data record                                                                            |
| AT             | Assets – Total/Liabilities and Stockholders’ Equity – Total    | Total Assets (Gross)                                                                                                                                                                                   |
| CEQ            | Common Equity – Total                                          | Total Book Value minus Treasury Stock – Dollar Amount – Preferred                                                                                                                                      |
| CHE            | Cash and Short-Term Investments                                | Cash Special Deposits, Working Funds and Temporary Cash Investments                                                                                                                                    |
| CSHO           | Common Shares Outstanding                                      | Number of Shares Outstanding                                                                                                                                                                           |
| DLC            | Debt in Current Liabilities                                    | Debt – Long-Term Due Within One Year plus Debt – Short-Term – Total                                                                                                                                    |
| DLTT           | Long-Term Debt – Total                                         | Debt – Long-Term – Total                                                                                                                                                                               |
| INVT           | Inventories – Total                                            | Inventories plus Gas Stored Underground                                                                                                                                                                |
| IVST           | Short-Term Investments                                         | Special Deposits, Working Funds, and Temporary Cash Investments                                                                                                                                        |
| MIB            | Redeemable Noncontrolling Interest (Balance Sheet)             | Redeemable Noncontrolling Interest (Balance Sheet)                                                                                                                                                     |
| NI             | Net Income (Loss)                                              | Net Income plus Total Extraordinary Items Net of Taxes                                                                                                                                                 |
| OANCF          | Operating Activities – Net Cash Flow (Statement of Cash Flows) | Operating Activities – Net Cash Flow (Statement of Cash Flows)                                                                                                                                         |
| OIADP          | Operating Income After Depreciation                            | Operating Income Taxes – Total plus Operating Income – Total                                                                                                                                           |
| PI             | Pretax Income                                                  | Current Operating Earnings Before Income Tax plus Net Pretax Profit or Loss on Securities Sold or Redeemed                                                                                             |
| PSTK           | Preferred Stock – Carrying Value                               | Preferred Stock – Par Value                                                                                                                                                                            |
| RECT           | Receivables – Total                                            | Receivables (Net) plus Accrued Revenues Unbilled                                                                                                                                                       |
| SALE           | Sales (Net)                                                    | Operating Revenues – Total (Income Statement)                                                                                                                                                          |
| TXT            | Income Taxes – Total                                           | Operating Income Taxes – Total plus Nonoperating Income Taxes (Net)                                                                                                                                    |
| XSGA           | Selling, General, and Administrative Expense                   | Salaries and Wages of Officers and Employees plus Pension and Employee Benefits plus Occupancy Expense of Bank Premises – Net plus Furniture and Equipment: Depreciation, Rental Cost, Servicing, Etc. |

**source: Chapter 4 Company Data and Table 1. Annual Xpressfeed Items Compared to Compustat Utility and Compustat Bank Items, Understanding the Data, Standard & Poor’s, 2011*